### PR TITLE
Move org.slf4j/slf4j-log4j12 into :dev profile (fixes #1)

### LINKED ISSUE #1: Remove dependency on org.slf4j/slf4j-log4j12?
[`project.clj` have a dependency on `slf4j-log4j12`](https://github.com/mpenet/sextant/blob/daadc166564d8333c92511cdabc0232aa97fa3ee/project.clj#L6). This dependency is superfluous as it is the binding between slf4j logging API and Log4j 1.2 logger. Thus it forces projects using this dependency to either use Log4j 1.2 or exclude this dependency.

I believe it can safely be removed (or moved into the `:dev` profile to remove some warnings at compile time).

If you agree I can make a PR 😄 .

### PR DESCRIPTION
**Pull request by rborer**
Also bump clojure, component & slf4j versions.

### CODE REVIEW

**Comment by mpenet** [comment]
Thanks. 

It's available as 1.1.0 on clojars

**Comment by rborer** [comment]
Thanks. I does not have the expected effect, so here comes #3 😉

**Comment by mpenet** [comment]
Shouldn't a dev profile without provided/scope be enough? 

I get that pom when uberjar or jar: 

```xml
<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>cc.qbits</groupId>
  <artifactId>sextant</artifactId>
  <packaging>jar</packaging>
  <version>1.1.0</version>
  <name>sextant</name>
  <description>Decode locations from things</description>
  <scm>
   ...
  </scm>
  <build>
    <sourceDirectory>src/clj</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>
    <resources>
      <resource>
        <directory>resources</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>resources</directory>
      </testResource>
    </testResources>
    <directory>target</directory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins>
      <plugin>
...
      </plugin>
    </plugins>
  </build>
  <repositories>
  ...
  </repositories>
  <dependencyManagement>
    <dependencies/>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>1.9.0</version>
    </dependency>
    <dependency>
      <groupId>com.stuartsierra</groupId>
      <artifactId>component</artifactId>
      <version>0.3.2</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.25</version>
    </dependency>
  </dependencies>
</project>

```

**Comment by rborer** [comment]
You're absolutely right... I was searching too deep for a solution 🤦‍♂️ .

**Pull request merged**
